/**
 * Vuetify 설치하면 자동으로 생성되는 파일.
 * 
 * This is a file that is generated by Vuetify
 */
import Vue from 'vue';
import Vuetify from 'vuetify/lib/framework';

Vue.use(Vuetify);

export default new Vuetify({
});
